
from __future__ import annotations

import argparse
import json
import os
import time
import zlib
from pathlib import Path
from typing import Any, Callable, Iterator, Sequence


_PROCESS_START = time.time()


def add_common_arguments(parser: argparse.ArgumentParser) -> argparse.ArgumentParser:
    parser.add_argument("--manifest", help="Input JSONL generated by WorkerStage")
    parser.add_argument("--output-dir", help="Output directory")
    parser.add_argument(
        "--prewarm",
        action="store_true",
        help="Load the model and exit to validate weights and available device memory.",
    )
    return parser


def distribution() -> tuple[int, int, int]:

    return (
        int(os.environ.get("RANK", "0")),
        int(os.environ.get("LOCAL_RANK", "0")),
        int(os.environ.get("WORLD_SIZE", "1")),
    )


def staged_name(repo_id: str) -> str:

    return repo_id.replace("/", "__")


def _staged_copy(repo_id: str) -> str | None:

    root = os.environ.get("ANNOT_LOCAL_WEIGHTS")
    if not root:
        return None
    candidate = Path(root) / staged_name(repo_id)
    return str(candidate) if (candidate / ".complete").exists() else None


def resolve_model_dir(value: str) -> str:

    path = Path(value)
    if path.exists():
        return str(path)

    staged = _staged_copy(value)
    if staged is not None:
        return staged

    from huggingface_hub import snapshot_download

    fallback = os.environ.get("HF_HUB_CACHE_FALLBACK")
    for cache_dir in (None, fallback):
        if cache_dir is not None and not Path(cache_dir).exists():
            continue
        try:
            return snapshot_download(value, cache_dir=cache_dir, local_files_only=True)
        except Exception:  # noqa: BLE001 -  miss
            continue
    return snapshot_download(value)


def read_manifest(path: str | Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    with Path(path).open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


class RankWriter:
    def __init__(self, output_dir: str | Path, rank: int):
        self.path = Path(output_dir) / f"rank_{rank:04d}.jsonl"
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.completed: set[str] = set()
        if self.path.exists():
            self._truncate_torn_tail()
            for line in self.path.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if not line:
                    continue
                try:
                    sample_id = json.loads(line).get("sample_id")
                except json.JSONDecodeError:

                    continue
                if sample_id:
                    self.completed.add(str(sample_id))
        self._handle = self.path.open("a", encoding="utf-8")
        self.processed = 0
        self.failed = 0

    def _truncate_torn_tail(self) -> None:

        with self.path.open("rb+") as handle:
            handle.seek(0, os.SEEK_END)
            size = handle.tell()
            if size == 0:
                return
            handle.seek(size - 1)
            if handle.read(1) == b"\n":
                return

            block = 65536
            position = size
            while position > 0:
                start = max(0, position - block)
                handle.seek(start)
                chunk = handle.read(position - start)
                index = chunk.rfind(b"\n")
                if index != -1:
                    handle.truncate(start + index + 1)
                    return
                position = start
            handle.truncate(0)

    def write(self, row: dict[str, Any]) -> None:
        self._handle.write(json.dumps(row, ensure_ascii=False) + "\n")


        self._handle.flush()
        if row.get("error"):
            self.failed += 1
        else:
            self.processed += 1

    def write_error(self, sample_id: Any, exc: BaseException) -> None:
        self.write({"sample_id": sample_id, "error": f"{type(exc).__name__}: {exc}"})

    def close(self) -> None:
        self._handle.close()

    def __enter__(self) -> "RankWriter":
        return self

    def __exit__(self, *_: object) -> None:
        self.close()


def shard_rank(sample_id: Any, world_size: int) -> int:

    return zlib.crc32(str(sample_id).encode("utf-8")) % max(1, int(world_size))


def assigned_records(
    records: Sequence[dict[str, Any]], rank: int, world_size: int, completed: set[str]
) -> list[dict[str, Any]]:

    return [
        record
        for record in records
        if shard_rank(record.get("sample_id"), world_size) == rank
        and str(record.get("sample_id")) not in completed
    ]


def batched(records: Sequence[dict[str, Any]], size: int) -> Iterator[list[dict[str, Any]]]:
    step = max(1, int(size))
    for start in range(0, len(records), step):
        yield list(records[start : start + step])


def run(
    args: argparse.Namespace,
    *,
    rank: int,
    world_size: int,
    handle: Callable[[dict[str, Any], RankWriter], None],
) -> None:

    if not args.manifest or not args.output_dir:
        raise ValueError("Non-prewarm mode requires --manifest and --output-dir")

    records = read_manifest(args.manifest)
    started = time.time()
    load_seconds = started - _PROCESS_START
    per_record: list[float] = []
    with RankWriter(args.output_dir, rank) as writer:
        todo = assigned_records(records, rank, world_size, writer.completed)
        for position, record in enumerate(todo):
            record_started = time.time()
            try:
                handle(record, writer)
            except Exception as exc:  # noqa: BLE001

                writer.write_error(record.get("sample_id"), exc)
            per_record.append(time.time() - record_started)
            if position and position % 50 == 0:
                rate = (position + 1) / max(time.time() - started, 1e-6)
                print(
                    f"[rank {rank}] {position + 1}/{len(todo)} "
                    f"{rate:.2f} items/s",
                    flush=True,
                )
        compute_seconds = time.time() - started
        summary = {
            "rank": rank,
            "processed": writer.processed,
            "failed": writer.failed,
            "seconds": round(compute_seconds, 1),


            "load_seconds": round(load_seconds, 1),
            "compute_seconds": round(compute_seconds, 1),
            "sec_per_record": (
                round(sum(per_record) / len(per_record), 2) if per_record else 0.0
            ),
            "slowest_record_sec": round(max(per_record), 2) if per_record else 0.0,
        }

    print("WORKER-SUMMARY " + json.dumps(summary, ensure_ascii=False), flush=True)


def setup_device(local_rank: int):

    import torch

    if torch.cuda.is_available():
        torch.cuda.set_device(local_rank)
        return torch.device(f"cuda:{local_rank}")
    return torch.device("cpu")
